### ISSUE TITLE
Tracking Issue for transactional States

### ISSUE THREAD

**Issue by JustusFluegel** [NicMcPhee/rust-ga#128]
This is a tracking issue for implementing transactional states. Since this is a huge changeset it was necessary to split this up into multiple pr's implementing independent features. ( This issue is based on #6 re-implementing the there made changes as a starting point )

- [ ] Move to &mut state instead of passing around the state directly
- [ ] General Error improvements
    - [ ] Remove State from Error types
    - [ ] Add `SpecifySeverity` Trait
    - [ ] Split up `StackError` into `OverflowError` and `UnderflowError`
- [ ] `ArrayLike` Trait and implementation for arrays and tuples
- [ ] Implement Stack-Manipulation Traits
    - [ ] GetAt / GetHead / GetTail
    - [ ] PopAt / PopHead / PopTail
    - [ ] PushAt / PushHead / PushTail
    - [ ] DiscardAt / DiscardHead / DiscardTail
    - [ ] ExtendAt / ExtendHead / ExtendTail
    - [ ] Size / Capacity
- [ ] Implement State-Manipulation Traits
    - [ ] GetAtIn / GetHeadIn / GetTailIn
    - [ ] PopAtIn / GetHeadIn / GetTailIn
    - [ ] PushAtIn / PushHeadIn / PushTailIn
    - [ ] DiscardAtIn / DiscardHeadIn / DiscardTailIn
    - [ ] ExtendAtIn / ExtendHeadIn / ExtendTailIn
    - [ ] SizeOf / CapacityOf
- [ ] Implement State Traits (State / StateMut and Stack / StackMut)
- `Transaction` Trait and corresponding `CreateTransaction` Trait (`.new_transaction()`, ...)
    - [ ] `StateTransaction` Trait
    - [ ] `WrapperTransaction` Trait
    - [ ] `TryTransaction` Trait
    - [ ] `StackTransaction` Trait
- Implement example transactions
    - [ ] Additive
    - [ ] Subtractive
    - [ ] Multi-Step
    - ...

Further Tasks
- [ ] Benchmark Transactions

**Comment by NicMcPhee** [comment]
Wow – this is really impressive – thanks!

A couple of thoughts:

First, this seems like way more than just about transactional states, and more like a roadmap for a whole host of things that we've talked about. Is this really more like an early draft of a roadmap to v1? Or just a broader roadmap of "stuff it would be good to do"?

Second, I certainly agree that this would be _way_ too much for one issue or PR. It might make sense to try to connect this to the existing issues and create new issues for things that we probably want to address in the near-ish future. I would see, for example, "Remove `State` from `Error` types" (which I am probably finally convinced about) as a stand-alone issue and PR that really doesn't have much to do with transactional states _per se_ (although doing that might make transactional states easier to implement).

That said, having everything here _as well_ as a kind of "big picture" view of the plans seems like a really good idea, and I really appreciate this.

**Comment by JustusFluegel** [comment]
Well I implemented a lot of this originally in #6 as part of creating transactions so I kept it here mostly, but yea it might make sense to split this up into even more issues. It was kinda more intended as a "roadmap" to transactional states in that sense, I was intending to add  a link to the corresponding pr after each item once I've gotten to that and then we have a overview here on what is done and what isn't
