### ISSUE TITLE
Tracking issue for general performance improvements

### ISSUE THREAD

**Issue by JustusFluegel** [NicMcPhee/rust-ga#61]
- [ ] random number generation
    - [ ] HashMaps (https://github.com/NicMcPhee/rust-ga/issues/11)
    - [ ] RNG choice (https://github.com/NicMcPhee/rust-ga/issues/27)
    - [ ] passing in different RNG's (https://github.com/NicMcPhee/rust-ga/issues/18)
